arch: arm64-graviton2
virt: vm
os: linux
dist: focal
group: edge

language: bash

env:
  - CI_NAME=travis DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - grep -i -e "BogoMIPS" /proc/cpuinfo
  - grep -i -e "MemTotal" /proc/meminfo
  - docker build --tag edgyr/internal-build-dependencies:latest internal-build-dependencies
  - docker build --tag edgyr/internal-ghc-8.2:latest internal-ghc-8.2
  - docker build --tag edgyr/internal-cabal-3.0:latest internal-cabal-3.0
  - docker build --tag edgyr/internal-cabal-3.2:latest internal-cabal-3.2
  - docker build --tag edgyr/internal-ghc-8.6:latest internal-ghc-8.6
  - docker build --tag edgyr/internal-pandoc:latest internal-pandoc
  - docker build --tag edgyr/internal-r:latest internal-r
  - docker build --tag edgyr/internal-rstudio-server:latest internal-rstudio-server
  - docker build --tag edgyr/edgyr:latest edgyr
