arch: arm64
os: linux
dist: bionic
language: bash
env:
  - CI_NAME=travis DOCKER_CLI_EXPERIMENTAL=enabled
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
  - grep "model name" /proc/cpuinfo
  - cat /proc/meminfo
  - docker buildx version
  - docker buildx create --use aardvark
  - docker buildx build --tag edgyr/internal-r-source:latest internal-r-source 
  - docker buildx build --tag edgyr/internal-pandoc-source:latest internal-pandoc-source 
