arch: arm64-graviton2
virt: vm
os: linux
dist: focal
group: edge

language: bash

env:
  - CI_NAME=travis DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-arm64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

script:
  - grep -i -e "BogoMIPS" /proc/cpuinfo
  - grep -i -e "MemTotal" /proc/meminfo
  - docker buildx version
  - travis_wait 20 docker build --tag edgyr/internal-r-source:latest internal-r-source 
  - travis_wait 20 docker build --tag edgyr/internal-pandoc-source:latest internal-pandoc-source 
  - travis_wait 20 docker build --tag edgyr/internal-rstudio-source:latest internal-rstudio-source 
  - travis_wait 20 docker build --tag edgyr/edgyr:latest edgyr 
